### PR TITLE
Convexity offset

### PR DESCRIPTION
**Pull request by emagdalenaC2i**

### CODE REVIEW

**Comment by emagdalenaC2i** [comment]
@mbartlett21 If you agree with this changes in the UI then I will create other PR to change the welds convexity dimensions

**Comment by mbartlett21** [comment]
Flat Butt may have convex edge, could you add that in?
Also, you'll have to change the title of this PR to merge it

**Comment by emagdalenaC2i** [comment]
@mbartlett21 do you mean Concave in square butts??

**Comment by mbartlett21** [comment]
Yes

**Comment by emagdalenaC2i** [comment]
I could integrate ButtShape and FilletShape anums, and let the concave option available for all the weld types. Are you agree?

**Comment by mbartlett21** [comment]
Yes

**Comment by emagdalenaC2i** [comment]
@mbartlett21 done
I will add the code to change the dimensions of the convexity in other PR, so please check this one and approve it if you agree

**Pull request merged**
