### PR TITLE
SCARF_BUTT_WELD and code review

### PR DESCRIPTION
**Pull request by emagdalenaC2i**

### CODE REVIEW

**Comment by mbartlett21** [comment]
This doesn't work in Onshape, can you please fix?

**Comment by emagdalenaC2i** [comment]
@mbartlett21 it should work fine now

**Comment by mbartlett21** [comment]
It should reflect the convex/flat/concave option on the bottom.
It also goes the wrong way sometimes:
image

**Comment by emagdalenaC2i** [comment]
@mbartlett21 The convex/flat/concave option on the bottom should be added as a Bead joint. See #53 
It is like in a square butt weld (witout the side 2 option)
captura
It also goes the wrong way sometimes? Please, explain more in detail

**Comment by mbartlett21** [comment]
In another PR, could we possibly merge `SCARF_BUTT_WELD` and `SQUARE_BUTT_WELD`?

**Comment by emagdalenaC2i** [comment]
@mbartlett21 actually I don't know. That was my first idea but I think it would be better if we have 2 different options

**Comment by mbartlett21** [comment]
Well, in #65 It does rename zero-angle welds to Square butt welds

**Comment by emagdalenaC2i** [comment]
@mbartlett21 but, we can use the Editing Logic Function
So, If the user have selected a SCARF_BUTT_WELD and set the angle to 0, we can change to a SQUARE_BUTT_WELD

**Comment by mbartlett21** [comment]
I think maybe just leave it for now.

**Comment by emagdalenaC2i** [comment]
Ok, so... are we ready for the release of the version 1.0 ???

**Comment by emagdalenaC2i** [comment]
@mbartlett21 are you agree?

**Comment by mbartlett21** [comment]
Yes

**Comment by emagdalenaC2i** [comment]
Ok, I 'll update the issues 1.0 and 2.0
@mbartlett21 Could you create a new version in Onshape with the License tab.
I 'll also working in a Part Studio with samples to show in the PDF tab with the description

**Comment by mbartlett21** [comment]
Could you do the license tab and I do the example PDF?

**Comment by emagdalenaC2i** [comment]
ok

**Comment by mbartlett21** [comment]
I just added my name, etc. to the license.
Do you want to create a pull request?

**Comment by emagdalenaC2i** [comment]
I did, you are too fast ;-)

**Pull request merged**
