### PR TITLE
Refactoring setWeldNumbers

### PR DESCRIPTION
**Pull request by emagdalenaC2i**
This will be used in another PR that integrates vButtWeld and doubleVButtWeld into a single funtion

### CODE REVIEW

**Comment by emagdalenaC2i** [comment]
@mbartlett21 We will need this if we want to create other weld types as described in #2 
Square, U, Bevel V, J should be the first one to integrate

**Comment by mbartlett21** [comment]
Should we use a UI like Catia for the different welds?
https://www.catiadesign.org/_doc/v5r14/catpdfwd1ug_C2/wd1ug.pdf#page=51&zoom=100,0,0

**Comment by mbartlett21** [comment]
@emagdalenaC2i 
Should we use a UI like Catia for the other types of welds?
https://www.catiadesign.org/_doc/v5r14/catpdfwd1ug_C2/wd1ug.pdf#page=51&zoom=100,0,0

**Comment by emagdalenaC2i** [comment]
Well FS UI are very limited right now. We can't add images...
I think we can handle properly with the enum WeldType and some specific annotations for some weldtypes

**Comment by mbartlett21** [comment]
I was meaning for the inputs...

**Pull request merged**
