### PR TITLE
Butt joints with several edges

### PR DESCRIPTION
**Pull request by emagdalenaC2i**

### CODE REVIEW

**Comment by mbartlett21** [comment]
Will you need to use
```
var subId = id + unstableIdComponent(i);
setExternalDisambiguation(context, subId, edge1);
``` and replace all instances of `id` with `subId`

**Comment by mbartlett21** [comment]
I'd want to use `setExternalDisambiguation`, otherwise the `Id`s will get mixed up if the `Query` is in a different order.

**Comment by emagdalenaC2i** [comment]
@mbartlett21 ok, done

**Comment by mbartlett21** [comment]
You can merge now

**Pull request merged**
