### PR TITLE
FilletShape.FLAT

### PR DESCRIPTION
**Pull request by emagdalenaC2i**

### CODE REVIEW

**Comment by mbartlett21** [comment]
I'm not sure this will work very well with `endFaces[]`.
You may need to update it to make sure it doesn't use the edge there

**Comment by emagdalenaC2i** [comment]
There a few issues with Mitter and Round options. But I will create a new PR to fix that

In this sample the feature of the left fails with Mitter
captura

In this example both mitter and round fail
captura2

**Comment by mbartlett21** [comment]
@emagdalenaC2i You can merge this if you want.
I'll leave it up to you.

**Comment by emagdalenaC2i** [comment]
@mbartlett21 Ok, you can merge ;-)

**Pull request merged**
