### PR TITLE
try silent opReplaceFace

### PR DESCRIPTION
**Pull request by emagdalenaC2i**

### CODE REVIEW

**Comment by mbartlett21** [comment]
I'd still rather just have `try` on these, as it needs to be fixed for convex faces.

**Comment by emagdalenaC2i** [comment]
ok, I close this PR then

**Comment by emagdalenaC2i** [comment]
@mbartlett21 You can merge this one if you want

**Comment by mbartlett21** [comment]
I'd still rather make this just try, but you can merge if you want

**Comment by emagdalenaC2i** [comment]
No, we can let it without silent and llok for a better solution
I'll close this PR

**Pull request closed without merging**
