### PR TITLE
(IMP) Code review

### PR DESCRIPTION
**Pull request by emagdalenaC2i**
Neaten up code, UI

### CODE REVIEW

**Comment by emagdalenaC2i** [comment]
@mbartlett21 I just added the header and some comments
You can merge if you want.

There is 1 conflicting file "weld.fs.js" because you update the master branch directly instead of create a new branch and create a PR ;-)

**Comment by mbartlett21** [comment]
You may have to merge from mine again :smile: 
I just added a commit to fix some trimming

**Comment by emagdalenaC2i** [comment]
Take a look to that horizontal enum
I think that will work very well, and there a a few more options that could be included in settings: color, Custom PropertiesId...

What do you think?

**Comment by mbartlett21** [comment]
@emagdalenaC2i 
Maybe have a third option with `annotation { "Hidden" : true }` and make it default for calling from FS then

**Comment by emagdalenaC2i** [comment]
@mbartlett21  I don't understand... Are you talking about a third option hidden in the horizontal enum? for what?
And what do you want to call from FS?

**Comment by mbartlett21** [comment]
@emagdalenaC2i 
I am meaning like this code here:
https://cad.onshape.com/documents/c080da1e327f87ccaa529a78/w/07e42653b60c2bbf2709bb2d/e/af68b564f0aef8bc8846d323
It adds a third option that is hidden and is the default when calling from FS

**Comment by mbartlett21** [comment]
The enum is now:
```javascript
/**
 * Feature and settings options
 *
 * @value FEATURE : Weld Feature.
 *
 * @value SETTINGS : Weld Settings.
 */
export enum WeldFeatureSettingsSelection
{
    annotation { "Name" : "Welds" }
    FEATURE,
    annotation { "Name" : "Settings" }
    SETTINGS,
    annotation { "Hidden" : true }
    SHOW_ALL
}
```
and the defaults in the feature are:
```javascript
    }, {
            weldFeatureSettingsSelection : WeldFeatureSettingsSelection.SHOW_ALL,
            filletPropagation : false
        });
```
Can I edit your fork to reflect this?

**Comment by emagdalenaC2i** [comment]
@mbartlett21 I see the code, but I don't know what's the difference runnin the FS with this hidden option

**Comment by emagdalenaC2i** [comment]
@mbartlett21 you can merge this PR if you wish
I have just finished the review of the code ;-) Gret work!!!

**Comment by emagdalenaC2i** [comment]
@mbartlett21 The conflist are solved now

**Pull request merged**
