### PR TITLE
Add Fillet size and height options

### LINKED ISSUE #26: fillet joints - wrong dimesnions
To fillet joints - these are proper dimensions of fillet joint - triangle inscribed in weld connection: 
image
And this is how it looks like now:
pachwina
There is also not possible to choose between "a" dimension and "z" dimension (and this is quite useful)

### PR DESCRIPTION
**Pull request by emagdalenaC2i**
FIX #26

### CODE REVIEW

**Comment by mbartlett21** [comment]
Can you add an option to measure perpendicular?

**Comment by emagdalenaC2i** [comment]
Dou you men keep the line
`var size = definition.filletSize / sin(angle);`
as it was?

**Comment by mbartlett21** [comment]
Yes, or add that as an option for the user

**Comment by emagdalenaC2i** [comment]
With 
`var size = definition.filletSize / sin(angle);`
the dimension of the weld will change in no perpendicular faces, like in the image below (the length of this edge will chage to 7.071 mm)
captura

**Comment by emagdalenaC2i** [comment]
@mbartlett21 you can see https://user-images.githubusercontent.com/45488807/49429735-8c4a1880-f7a9-11e8-88bc-eb5432d73dfd.PNG

I think we should only allow to set a or z options, but if you want we can add that as an option to the FilletDimension enum. What name dou you want?

**Comment by mbartlett21** [comment]
Maybe just call it perpendicular for now.

**Comment by emagdalenaC2i** [comment]
@mbartlett21 Ok, done

**Pull request merged**
