### PR TITLE
Update arc height in V-Butt Welds

### PR DESCRIPTION
**Pull request by emagdalenaC2i**
Why it was distOut / 5?

### CODE REVIEW

**Comment by emagdalenaC2i** [comment]
It may be better to define an offeset for the convex and concave shapes
9808913_orig
image530

**Comment by emagdalenaC2i** [comment]
It will be like this
```
            annotation { "Name" : "Shape", "UIHint" : ["REMEMBER_PREVIOUS_VALUE", "SHOW_LABEL"] }
            definition.buttShape is ButtShape;

            if (definition.buttShape == ButtShape.CONVEX)
            {
                annotation { "Name" : "Offset", "UIHint" : "REMEMBER_PREVIOUS_VALUE" }
                isLength(definition.buttOffset, BLEND_BOUNDS);
            }
```

**Comment by mbartlett21** [comment]
Do you want to add the code for that?

**Comment by emagdalenaC2i** [comment]
@mbartlett21 Ok, I will close this PR and create a new one with the Offset annotation option

**Pull request closed without merging**
