### PR TITLE
FilletWeld Limit to 1 face in side 1

### PR DESCRIPTION
**Pull request by emagdalenaC2i**
This option could help to fix some issues and I don't believe that the functionality of the Weld FeatureScript would be limited with it

### CODE REVIEW

**Comment by emagdalenaC2i** [comment]
@mbartlett21 this could be temporary. Once we fix the issues with non panar and non perpendicular faces we could let again more than 1 face in side 1

**Comment by mbartlett21** [comment]
You may have to disable the tangent propagation for side 1, or do you want it still to propagate?

**Comment by emagdalenaC2i** [comment]
we can let it be for now

**Comment by mbartlett21** [comment]
Ok, Merged

**Pull request merged**
